version: "3"

services:
  database:
    container_name: ${MYSQL_NAME}
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${PUTI_ROOT}${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      - ${PUTI_ROOT}${MYSQL_LOG_PATH}:/var/log/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    networks:
      - db
    # this entrypoint and command can rewrite by entrypoint script
    entrypoint: ""
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"

  nginx:
    container_name: ${NGINX_NAME}
    build: 
      context: ./nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    depends_on:
      - puti
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${PUTI_ROOT}${NGINX_CONF_PATH}:/etc/nginx/nginx.conf
      - ${PUTI_ROOT}${NGINX_CONFD_PATH}:/etc/nginx/conf.d
      - ${PUTI_ROOT}${NGINX_CERT_PATH}:/etc/nginx/certs
      - ${PUTI_ROOT}${NGINX_LOG_PATH}:/var/log/nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${NGINX_HOST_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
    restart: always
    networks:
      - web

  puti:
    container_name: ${PUTI_NAME}
    image: puti/puti:${PUTI_VERSION}
    depends_on:
      - database
    volumes:
      - ${PUTI_ROOT}${PUTI_DATA_PATH}:/data/puti
      - ${PUTI_ROOT}${PUTI_LOG_PATH}:/data/logs/puti
    ports:
      - "${PUTI_HTTP_PORT_OUT}:${PUTI_HTTP_PORT}"
      - "${PUTI_HTTPS_PORT_OUT}:${PUTI_HTTPS_PORT}"
    restart: always
    networks:
      - db
      - web
    entrypoint: ["/usr/local/bin/wait-for-db.sh", "database:3306", "--", "docker-entrypoint.sh"]
    command: ["puti"]

networks:
  db:
  web:
