############################
# Builder image
############################
ARG GOLANG_BUILDER_VERSION=alpine
FROM golang:${GOLANG_BUILDER_VERSION} AS builder

RUN apk update && apk add --no-cache build-base git tzdata && update-ca-certificates

WORKDIR /data
RUN wget -O puti.zip https://github.com/puti-projects/puti/archive/master.zip && \
    unzip puti.zip && \
    mv puti-master puti && \ 
    chmod -R 777 puti && \
    rm -f puti.zip

WORKDIR /data/puti
# Build the binary.
RUN make


############################
# Usage image
############################
FROM alpine

# Import from the builder.
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=builder /data/puti /puti

# Copy files
# # binary
# COPY --from=builder /data/puti/puti /puti/
# # config
# COPY --from=builder /data/puti/configs /puti/configs
# # backend html
# COPY --from=builder /data/puti/console /puti/console
# # theme path
# COPY --from=builder /data/puti/theme /puti/theme
# # upload path
# COPY --from=builder /data/puti/uploads /puti/uploads
# # other static file
# COPY --from=builder /data/puti/assets /puti/assets

WORKDIR /puti

EXPOSE 8000 8080
# Run the puti binary.
CMD ["./puti"]